# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YHPShareView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YHPShareView
  pod 'Masonry', '~> 0.6.4'

  target 'YHPShareViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YHPShareViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
